#!/usr/bin/env python3
import os, sys
import argparse
import random

DIR = os.path.dirname(os.path.realpath(__file__))
# include original ponysay
sys.path.append(os.path.join(DIR, 'src'))


if __name__ == "__main__":
    # parse options (for now only two)
    parser = argparse.ArgumentParser(
            description="Rick & Morty quotes of the day with ponies included!")
    parser.add_argument('-r', action="store_const", dest="character",
            const="Rick", help="Rick's quote (default)")
    parser.add_argument('-m', action="store_const", dest="character",
            const="Morty", help="Morty's quote")
    parser.set_defaults(character="Rick")
    args = parser.parse_args()
    ponies_dir = os.path.join(DIR, 'ponies', args.character)
    random_pony = random.choice([os.path.join(ponies_dir,f)
        for f in os.listdir(ponies_dir)])

    # if it's piped text use it, else get random quote
    if not sys.stdin.isatty():
        quote = sys.stdin.read()
    else:
        quotes_dir = os.path.join(DIR, 'quotes', args.character)
        random_quote_file = random.choice([os.path.join(quotes_dir, f)
            for f in os.listdir(quotes_dir)])
        with open(random_quote_file) as f:
            quote = f.read()

    # run ponysay with faked args
    sys.argv = ['ricksay', '-f', random_pony, '--', quote]
    from main import main 
    main()
