#!/usr/bin/env python3
import os, sys
import argparse
import random

DIR = os.path.dirname(os.path.realpath(__file__))
# include original ponysay
sys.path.append(os.path.join(DIR, 'src'))


if __name__ == "__main__":
    # TODO: try click
    parser = argparse.ArgumentParser(
            description="Rick & Morty quotes of the day with ponies!")
    parser.add_argument('-r', action="store_const", dest="character",
            const="Rick", help="Rick's quote (default)")
    parser.add_argument('-m', action="store_const", dest="character",
            const="Morty", help="Morty's quote")
    parser.set_defaults(character="Rick")
    args = parser.parse_args()
    ponies_dir = os.path.join(DIR, 'ponies', args.character)
    random_pony = random.choice([os.path.join(ponies_dir,f)
        for f in os.listdir(ponies_dir)])
    quotes_dir = os.path.join(DIR, 'quotes', args.character)
    random_quote_file = random.choice([os.path.join(quotes_dir, f)
        for f in os.listdir(quotes_dir)])
    # todo: check stdin first
    with open(random_quote_file) as f:
        random_quote = f.read()

    sys.argv = ['ricksay', '-f', random_pony, '--', random_quote]
    from main import main 
    main()
